/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * SPDX-License-Identifier: MPL-2.0
 */
using LLMCodeExporter.Core.Interfaces;

namespace LLMCodeExporter.Core.Models;

public enum ExportMode
{
    Compact,
    Balanced,
    Full
}

public enum ExportFormat
{
    Markdown,
    PlainText,
    Json,
    MarkdownWithJson
}

public class ExportSettings : IExportSettings
{
    // === IExportSettings implementation ===
    public ExportMode Mode { get; set; } = ExportMode.Balanced;
    public ProjectType ProjectType { get; set; } = ProjectType.AutoDetect;
    public bool IncludeComments { get; set; } = true;
    public bool Minify { get; set; } = false;
    public string[] ExcludeFolders { get; set; } = new[] { "bin", "obj", ".vs", "packages" };
    public string[] ExcludeFiles { get; set; } = Array.Empty<string>();
    public long MaxFileSize { get; set; } = 10 * 1024 * 1024; // 10 MB
    public int MaxTokens { get; set; } = 100000;

    // === Базовые настройки ===
    public bool RemoveEmptyLines { get; set; } = true;
    public bool RemoveComments { get; set; } = false;
    public bool FilterBuildFolders { get; set; } = true;
    public ExportFormat Format { get; set; } = ExportFormat.Markdown;
    public string[] FileExtensions { get; set; } = new[] { "*.cs" };
    public string OutputDirectory { get; set; } = GetDefaultOutputDirectory();

    // === Новые настройки для гибридного режима ===
    public Language BackendLanguage { get; set; } = Language.CSharp;
    public Language FrontendLanguage { get; set; } = Language.JavaScript;

    public List<string> ExcludePatterns { get; set; } = new();
    public List<string> IncludeOnlyPatterns { get; set; } = new();
    public int MethodCollapseThreshold { get; set; } = 50;
    public bool ConsolidateUsings { get; set; } = true;
    public bool CollapseAutoGenerated { get; set; } = true;
    public bool GenerateQuickLinks { get; set; } = true;
    public List<string> EntryPoints { get; set; } = new()
    {
        "Program.cs", "Startup.cs", "ApplicationRunner.cs", "Main.cs"
    };

    // === Пресеты ===

    public void ApplyPythonProjectPreset()
    {
        FileExtensions = new[] { "*.py", "*.md" };
        FilterBuildFolders = true;
        ExcludeFolders = Array.Empty<string>();
        ExcludePatterns = new() { "*.pyc", "*.pyo", "*.pyd" };
        Mode = ExportMode.Full;
    }

    public void ApplyWebAppPreset()
    {
        FileExtensions = new[] {
            "*.js", "*.jsx", "*.ts", "*.tsx",
            "*.css", "*.scss", "*.sass", "*.less",
            "*.html", "*.htm",
            "*.json", "*.xml", "*.svg"
        };
        FilterBuildFolders = true;
        ExcludeFolders = new[] { "node_modules", "dist", "build", ".git", ".next", ".nuxt", ".cache" };
        ExcludePatterns = new() { "*.min.js", "*.min.css", "*.bundle.js" };
        Mode = ExportMode.Full;
        EntryPoints = new List<string>
        {
            "index.html", "main.js", "app.js", "app.ts", "styles.css"
        };
    }

    public void ApplyBackendOnlyPreset()
    {
        ExcludePatterns.Add("*.Designer.cs");
        ExcludePatterns.Add("Forms");
        ExcludePatterns.Add("Views");
        ExcludePatterns.Add("UI");
        ExcludePatterns.Add("*.xaml.cs");
        ExcludePatterns.Add("*.razor");
    }

    public void ApplyDomainServicesPreset()
    {
        IncludeOnlyPatterns.Add("Domain");
        IncludeOnlyPatterns.Add("Services");
        IncludeOnlyPatterns.Add("Application");
        IncludeOnlyPatterns.Add("Core");
    }

    public void ApplyCompactAggressivePreset()
    {
        Mode = ExportMode.Compact;
        RemoveComments = true;
        RemoveEmptyLines = true;
        CollapseAutoGenerated = true;
        MethodCollapseThreshold = 30;
    }

    /// <summary>
    /// Применяет пресет для гибридных проектов, используя выбранные BackendLanguage и FrontendLanguage.
    /// </summary>
    public void ApplyHybridPreset()
    {
        var backendSettings = LanguageSettings.ForLanguage(BackendLanguage);
        var frontendSettings = LanguageSettings.ForLanguage(FrontendLanguage);
        var combined = LanguageSettings.Combine(backendSettings, frontendSettings);

        // Преобразуем расширения в формат "*.ext"
        FileExtensions = combined.FileExtensions.Select(ext => $"*{ext}").ToArray();
        ExcludeFolders = combined.ExcludeFolders;
        EntryPoints = combined.EntryPoints.ToList();
        FilterBuildFolders = true;
        ExcludePatterns = new List<string>
        {
            "*.Designer.cs", "*.min.js", "*.min.css", "*.bundle.js"
        };
        Mode = ExportMode.Balanced;
        GenerateQuickLinks = true;
        RemoveComments = false; // для JS/CSS удаление комментариев может нарушить код
    }

    public static string GetDefaultOutputDirectory()
    {
        string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
        string outputPath = Path.Combine(documentsPath, "LLMCodeExporter", "Exports");
        if (!Directory.Exists(outputPath))
            Directory.CreateDirectory(outputPath);
        return outputPath;
    }
}