/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * SPDX-License-Identifier: MPL-2.0
 */
﻿using LLMCodeExporter.Core.Interfaces;

namespace LLMCodeExporter.Core.Models;

/// <summary>
/// Режим экспорта - определяет уровень детализации
/// </summary>
public enum ExportMode
{
    /// <summary>
    /// Compact - только структура и сигнатуры (~30% от оригинала, ~30K токенов)
    /// </summary>
    Compact,
    /// <summary>
    /// Balanced - оптимизация больших методов (~50-70% от оригинала, ~50-70K токенов)
    /// </summary>
    Balanced,
    /// <summary>
    /// Full - весь код без изменений (100%, может быть 100K+ токенов)
    /// </summary>
    Full
}

public enum ExportFormat
{
    Markdown,
    PlainText
}

/// <summary>
/// Настройки экспорта проекта (реализует IExportSettings)
/// </summary>
public class ExportSettings : IExportSettings
{
    // === IExportSettings implementation ===
    public ExportMode Mode { get; set; } = ExportMode.Balanced;
    public ProjectType ProjectType { get; set; } = ProjectType.AutoDetect;
    public bool IncludeComments { get; set; } = true;
    public bool Minify { get; set; } = false;
    public string[] ExcludeFolders { get; set; } = new[] { "bin", "obj", ".vs", "packages" };
    public string[] ExcludeFiles { get; set; } = Array.Empty<string>();
    public long MaxFileSize { get; set; } = 10 * 1024 * 1024; // 10 MB
    public int MaxTokens { get; set; } = 100000;

    // === Базовые настройки (v1.0) ===
    public bool RemoveEmptyLines { get; set; } = true;
    public bool RemoveComments { get; set; } = false;
    public bool FilterBuildFolders { get; set; } = true;
    public ExportFormat Format { get; set; } = ExportFormat.Markdown;
    public string[] FileExtensions { get; set; } = new[] { "*.cs" };
    public string OutputDirectory { get; set; } = GetDefaultOutputDirectory();

    // === Новые настройки (v2.0) ===
    /// <summary>
    /// Паттерны для исключения файлов (например: "*.Designer.cs", "Forms", "*.g.cs")
    /// </summary>
    public List<string> ExcludePatterns { get; set; } = new();

    /// <summary>
    /// Включать ТОЛЬКО файлы по паттернам (например: "Domain", "Services")
    /// Если пусто - включаются все (кроме ExcludePatterns)
    /// </summary>
    public List<string> IncludeOnlyPatterns { get; set; } = new();

    /// <summary>
    /// Порог строк для сворачивания методов в Balanced режиме
    /// </summary>
    public int MethodCollapseThreshold { get; set; } = 50;

    /// <summary>
    /// Консолидировать using директивы в начало файла
    /// </summary>
    public bool ConsolidateUsings { get; set; } = true;

    /// <summary>
    /// Сворачивать авто-сгенерированные файлы (.Designer.cs, .g.cs)
    /// </summary>
    public bool CollapseAutoGenerated { get; set; } = true;

    /// <summary>
    /// Генерировать Quick Links навигацию
    /// </summary>
    public bool GenerateQuickLinks { get; set; } = true;

    /// <summary>
    /// Entry points для Quick Links (точки входа в приложение)
    /// </summary>
    public List<string> EntryPoints { get; set; } = new()
    {
        "Program.cs",
        "Startup.cs",
        "ApplicationRunner.cs",
        "Main.cs"
    };
    public void ApplyPythonProjectPreset()
    {
        FileExtensions = new[] { "*.py", "*.md" };
        FilterBuildFolders = true;

        // Ничего не режем по папкам, чтобы не убить весь проект
        ExcludeFolders = Array.Empty<string>();

        ExcludePatterns = new() { "*.pyc", "*.pyo", "*.pyd" };
        Mode = ExportMode.Full;
    }
    // ДОБАВИТЬ этот метод
    /// <summary>
    /// Preset: Web Application - JS, CSS, HTML файлы
    /// </summary>
    public void ApplyWebAppPreset()
    {
        FileExtensions = new[] {
        "*.js", "*.jsx", "*.ts", "*.tsx",
        "*.css", "*.scss", "*.sass", "*.less",
        "*.html", "*.htm",
        "*.json", "*.xml", "*.svg"
    };
        FilterBuildFolders = true;
        ExcludeFolders = new[] { "node_modules", "dist", "build", ".git", ".next", ".nuxt", ".cache" };
        ExcludePatterns = new() { "*.min.js", "*.min.css", "*.bundle.js" };
        Mode = ExportMode.Full;
        EntryPoints = new List<string>
    {
        "index.html",
        "main.js",
        "app.js",
        "app.ts",
        "styles.css"
    };
    }

    public static string GetDefaultOutputDirectory()
    {
        string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
        string outputPath = Path.Combine(documentsPath, "LLMCodeExporter", "Exports");
        if (!Directory.Exists(outputPath))
        {
            Directory.CreateDirectory(outputPath);
        }

        return outputPath;
    }

    // === Preset методы для быстрой настройки ===
    /// <summary>
    /// Preset: Backend Only - исключает UI файлы
    /// </summary>
    public void ApplyBackendOnlyPreset()
    {
        ExcludePatterns.Add("*.Designer.cs");
        ExcludePatterns.Add("Forms");
        ExcludePatterns.Add("Views");
        ExcludePatterns.Add("UI");
        ExcludePatterns.Add("*.xaml.cs");
        ExcludePatterns.Add("*.razor");
    }

    /// <summary>
    /// Preset: Domain + Services Only - только бизнес-логика
    /// </summary>
    public void ApplyDomainServicesPreset()
    {
        IncludeOnlyPatterns.Add("Domain");
        IncludeOnlyPatterns.Add("Services");
        IncludeOnlyPatterns.Add("Application");
        IncludeOnlyPatterns.Add("Core");
    }

    /// <summary>
    /// Preset: Compact Aggressive - максимальное сжатие
    /// </summary>
    public void ApplyCompactAggressivePreset()
    {
        Mode = ExportMode.Compact;
        RemoveComments = true;
        RemoveEmptyLines = true;
        CollapseAutoGenerated = true;
        MethodCollapseThreshold = 30;
    }


}