/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * SPDX-License-Identifier: MPL-2.0
 */
﻿using LLMCodeExporter.Core.Models;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace LLMCodeExporter.Tests.Unit.Core.Models
{
    [TestClass]
    public class ExportSettingsTests
    {
        [TestMethod]
        public void ApplyBackendOnlyPreset_SetsCorrectPatterns()
        {
            // Arrange
            var settings = new ExportSettings();

            // Act
            settings.ApplyBackendOnlyPreset();

            // Assert
            var excludePatterns = settings.ExcludePatterns.ToList();
            Assert.IsTrue(excludePatterns.Contains("*.Designer.cs"));
            Assert.IsTrue(excludePatterns.Contains("Forms"));
            Assert.IsTrue(excludePatterns.Contains("Views"));
            Assert.IsTrue(excludePatterns.Contains("UI"));
            Assert.IsTrue(excludePatterns.Count >= 5, $"Expected >=5 patterns, got {excludePatterns.Count}");
        }

        [TestMethod]
        public void ApplyDomainServicesPreset_SetsIncludeOnlyPatterns()
        {
            // Arrange
            var settings = new ExportSettings();

            // Act
            settings.ApplyDomainServicesPreset();

            // Assert
            var includePatterns = settings.IncludeOnlyPatterns.ToList();
            Assert.IsTrue(includePatterns.Contains("Domain"));
            Assert.IsTrue(includePatterns.Contains("Services"));
            Assert.IsTrue(includePatterns.Contains("Application"));
            Assert.IsTrue(includePatterns.Contains("Core"));
            Assert.AreEqual(4, includePatterns.Count, $"Expected 4 patterns, got {includePatterns.Count}");
        }

        [TestMethod]
        public void ApplyCompactAggressivePreset_SetsAggressiveSettings()
        {
            // Arrange
            var settings = new ExportSettings();

            // Act
            settings.ApplyCompactAggressivePreset();

            // Assert
            Assert.AreEqual(ExportMode.Compact, settings.Mode);
            Assert.IsTrue(settings.RemoveComments);
            Assert.IsTrue(settings.RemoveEmptyLines);
            Assert.IsTrue(settings.CollapseAutoGenerated);
            Assert.AreEqual(30, settings.MethodCollapseThreshold);
        }

        [TestMethod]
        public void GetDefaultOutputDirectory_ReturnsValidPath()
        {
            // Arrange & Act
            string path = ExportSettings.GetDefaultOutputDirectory();

            // Assert
            Assert.IsFalse(string.IsNullOrEmpty(path), "Path must not be null or empty");
            Assert.IsTrue(path.Contains("LLMCodeExporter"), "Must contain project name");
            Assert.IsTrue(path.Contains("Exports"), "Must contain Exports folder");

            // Проверяем только структуру пути, не существование директории
            Assert.IsTrue(!string.IsNullOrEmpty(Path.GetDirectoryName(path)));
        }
    }
}
