<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\LLMCodeExporter.Core\LLMCodeExporter.Core.csproj" />
		<ProjectReference Include="..\LLMCodeExporter.Infrastructure\LLMCodeExporter.Infrastructure.csproj" />
		<ProjectReference Include="..\..\LLMCode_Importer\LLMCode_Importer.csproj" />
	</ItemGroup>

</Project>